version: "3.6"

services:
  fyurr:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "app.py"]
    container_name: fyyur
    depends_on:
      - fyurr-db
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/
  fyurr-db:
    image: postgres
    container_name: postgres-fyurr
    env_file:
      - .env
    hostname: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
