version: "3.6"

services:
  fyyur:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "app.py"]
    container_name: fyyur
    depends_on:
      - fyyur-db
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/
  fyyur-db:
    image: postgres
    container_name: postgres-fyyur
    env_file:
      - .env
    hostname: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./sql/venues.sql:/tmp/venues.sql
      - ./sql/artists.sql:/tmp/artists.sql
      - ./sql/shows.sql:/tmp/shows.sql
