insert into artists
values (1,
        'Ms. Dawn Stevenson',
        array ['Spoken Word', 'Hip-Hop/Rap', 'Anime'],
        'Stephanieburgh',
        'Iowa',
        '001-087-660-0247',
        'www.facebook.com/penajessica972',
        true,
        'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'https://www.smith.info/',
        'grow ubiquitous paradigms'),
       (2,
        'Robert Hale',
        array ['Opera', 'Tex-Mex', 'Indie Pop'],
        'East Leslieborough',
        'Hawaii',
        '3466059047',
        'www.facebook.com/kayala616',
        true,
        'https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'https://rivera-martin.com/',
        'maximize distributed web-readiness'),
       (3,
        'David Montes',
        array ['Fitness & Workout', 'Anime', 'Disney'],
        'Marissamouth',
        'New Mexico',
        '706-351-9822',
        'www.facebook.com/jameskelly830',
        false,
        'https://images.pexels.com/photos/4067768/pexels-photo-4067768.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'https://spencer-olsen.com/',
        'cultivate open-source technologies'),
       (4,
        'Eric Cruz',
        array ['Singer/Songwriter', 'Karaoke', 'Indie Pop'],
        'Gonzaleztown',
        'Michigan',
        '(752)714-0072',
        'www.facebook.com/kendra93588',
        true,
        'https://images.pexels.com/photos/3586765/pexels-photo-3586765.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://www.brown-mercado.info/',
        'seize integrated interfaces'),
       (5,
        'Cassandra Anderson',
        array ['Electronic', 'Jazz', 'Progressive'],
        'Lake Audrey',
        'Michigan',
        '357.889.5376',
        'www.facebook.com/lbarajas358',
        false,
        'https://images.pexels.com/photos/610294/pexels-photo-610294.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://www.white.com/',
        'maximize innovative convergence'),
       (6,
        'Cassandra Mills',
        array ['Folk Music', 'Soundtrack', 'New Age'],
        'Benderfort',
        'Missouri',
        '+1-498-960-3024',
        'www.facebook.com/jamesjoshua512',
        true,
        'https://images.pexels.com/photos/4067765/pexels-photo-4067765.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'https://www.fisher-richard.com/',
        'deploy revolutionary deliverables'),
       (7,
        'Tyler Sosa',
        array ['Soundtrack', 'Comedy', 'Vocal'],
        'Emmastad',
        'Connecticut',
        '520.972.5206',
        'www.facebook.com/ebrady104',
        true,
        'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'https://www.moore.com/',
        'syndicate innovative functionalities'),
       (8,
        'Luis Malone',
        array ['Commercial', 'Opera', 'Karaoke'],
        'Walkerview',
        'Georgia',
        '211-155-2220',
        'www.facebook.com/aaronriley516',
        true,
        'https://images.pexels.com/photos/3775168/pexels-photo-3775168.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://sparks.info/',
        'transition holistic ROI'),
       (9,
        'Kevin Martinez',
        array ['Post-Disco', 'Enka', 'Dance )'],
        'Curryview',
        'Wyoming',
        '9576001799',
        'www.facebook.com/jessica92821',
        false,
        'https://images.pexels.com/photos/4067760/pexels-photo-4067760.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://green.info/',
        're-intermediate collaborative interfaces'),
       (10,
        'Matthew Gallagher',
        array ['German Folk', 'Electronic', 'Alternative'],
        'Lake Shirleyland',
        'Montana',
        '001-403-340-9423',
        'www.facebook.com/xcarter641',
        true,
        'https://images.pexels.com/photos/4067757/pexels-photo-4067757.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://www.french-gutierrez.info/',
        'evolve ubiquitous communities'),
       (11,
        'Thomas Mendez',
        array ['New Age', 'Jazz', 'Metal'],
        'Port Shawn',
        'Texas',
        '841.702.1471',
        'www.facebook.com/blackshawn865',
        false,
        'https://images.pexels.com/photos/4067754/pexels-photo-4067754.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://www.beard.com/',
        'seize holistic channels'),
       (12,
        'James Anderson',
        array ['Post-Disco', 'Opera', 'Tejano'],
        'Williamville',
        'Alabama',
        '951.018.2039',
        'www.facebook.com/tmoody997',
        false,
        'https://images.pexels.com/photos/4068303/pexels-photo-4068303.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'https://weaver.com/',
        'transition next-generation relationships'),
       (13,
        'Andrew Lee',
        array ['Blues', 'Easy Listening', 'New Age'],
        'Jenningsbury',
        'Wyoming',
        '+1-777-236-3522',
        'www.facebook.com/smorris491',
        true,
        'https://images.pexels.com/photos/4067761/pexels-photo-4067761.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://smith-smith.com/',
        'facilitate best-of-breed convergence'),
       (14,
        'Shannon Stout',
        array ['Blues', 'Post-Disco', 'Easy Listening'],
        'Mollytown',
        'Louisiana',
        '001-087-369-7277',
        'www.facebook.com/lisastevens411',
        true,
        'https://images.pexels.com/photos/4068300/pexels-photo-4068300.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://sanford.info/',
        'generate turn-key eyeballs'),
       (15,
        'Shannon Briggs PhD',
        array ['Easy Listening', 'Anime', 'Blues'],
        'North Nicole',
        'Arkansas',
        '301.093.3528',
        'www.facebook.com/laura75817',
        false,
        'https://images.pexels.com/photos/1374510/pexels-photo-1374510.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'https://www.harris-powers.biz/',
        'incentivize magnetic architectures'),
       (16,
        'Anna Booth',
        array ['Alternative', 'Latin', 'French Pop'],
        'East Hannahborough',
        'Missouri',
        '333.793.4131',
        'www.facebook.com/nfields498',
        true,
        'https://images.pexels.com/photos/4068293/pexels-photo-4068293.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'https://www.johnson.biz/',
        'cultivate wireless solutions'),
       (17,
        'Chelsea Morrison',
        array ['Soundtrack', 'German Pop', 'K-Pop'],
        'South Mary',
        'Virginia',
        '(272)218-2210',
        'www.facebook.com/allisonsimmons466',
        true,
        'https://images.pexels.com/photos/6482311/pexels-photo-6482311.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://www.riley.info/',
        'enable distributed communities'),
       (18,
        'Regina Mckenzie',
        array ['Blues', 'Jazz', 'Comedy'],
        'East Andrew',
        'California',
        '331.422.3859',
        'www.facebook.com/williskatherine218',
        true,
        'https://images.pexels.com/photos/6482323/pexels-photo-6482323.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://allen.org/',
        'disintermediate out-of-the-box portals'),
       (19,
        'Kevin Hayes',
        array ['Soundtrack', 'Fitness & Workout', 'Singer/Songwriter'],
        'Port Angela',
        'New Jersey',
        '+1-888-912-3290',
        'www.facebook.com/alexandria50966',
        true,
        'https://images.pexels.com/photos/6482312/pexels-photo-6482312.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'http://www.wilson.com/',
        'transition one-to-one portals'),
       (20,
        'Seth Williams',
        array ['Country', 'Commercial', 'R&B/Soul'],
        'Frankbury',
        'New York',
        '082-614-8010',
        'www.facebook.com/wjordan859',
        false,
        'https://images.pexels.com/photos/3792581/pexels-photo-3792581.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500 500w',
        'https://www.garcia.com/',
        'maximize front-end initiatives');

truncate artists cascade